const fs = require('fs');
const p = 'dist/index.html';
let h = fs.readFileSync(p, 'utf8');

const css = `html,body{margin:0!important;width:100%!important;height:100%!important;overflow:hidden!important;background:#F7F3EB!important}body{padding:0!important;display:block!important;min-height:100dvh!important;touch-action:pan-y;overscroll-behavior:none}.phone{width:100vw!important;height:100dvh!important;min-height:100dvh!important;max-width:none!important;border-radius:0!important;box-shadow:none!important}.screen{height:calc(100dvh - 54px)!important}@supports(height:100svh){body,.phone{height:100svh!important;min-height:100svh!important}.screen{height:calc(100svh - 54px)!important}}.quote-card{cursor:pointer}.quote-card .heart{position:relative;z-index:3}.specimen-section{border-top:1px solid var(--soft);padding:24px 0}.specimen-section:first-of-type{margin-top:36px}.specimen-section-title{display:grid;grid-template-columns:44px 1fr;gap:12px;align-items:center;margin:0 0 14px}.specimen-section-title .mono{color:var(--ink)}.specimen-section .acc-body{padding:0 0 0 56px}.specimen-section .dosgrid{padding-left:0}`;
if (!h.includes('/* streamlined-specimen-nav */')) h = h.replace('</style>', `/* streamlined-specimen-nav */${css}</style>`);

const patch = `
function openSpecimenFromToday(id){st.detail=id;st.returnTab='today';st.tab='gallery';save();detail()}
quoteCard=function(s,n){return \`<section class="quote-card" data-today-id="\${s.id}" onclick="openSpecimenFromToday('\${s.id}')"><div class="qmeta"><span class="mono">\${String(n).padStart(2,'0')} · \${s.domain}</span><button class="heart" id="save-\${s.id}" onclick="event.stopPropagation()">\${st.saved.has(s.id)?'♥':'♡'}</button></div><div class="quote-mark">“</div><h2 class="today-quote">\${s.quote}</h2><div class="source mono">\${s.source}</div></section>\`}
const originalGallery=gallery;
gallery=function(){originalGallery();attachGallerySwipe()}
function attachGallerySwipe(){let sx=0,sy=0,active=false;screen.ontouchstart=e=>{if(st.tab!=='gallery'||st.detail)return;let t=e.touches[0];sx=t.clientX;sy=t.clientY;active=true};screen.ontouchend=e=>{if(!active||st.tab!=='gallery'||st.detail)return;let t=e.changedTouches[0],dx=t.clientX-sx,dy=t.clientY-sy;active=false;if(dx>85&&Math.abs(dy)<70){st.tab='today';st.detail='';save();render()}}}
detail=function(){let s=specimenById(st.detail)||todayItems()[0],orig=st.orig===s.id;bump('opened',s.id);screen.innerHTML=\`<div class="detail-head"><button class="mono" id="close">×</button><div style="text-align:center"><div class="mono">Specimen</div><div class="mono muted" style="margin-top:12px">\${s.domain}</div></div><button class="heart" id="saveD">\${st.saved.has(s.id)?'♥':'♡'}</button></div><div class="mono muted" style="margin-bottom:18px">Specimen</div><h1 class="detail-title">\${s.title}</h1><p class="detail-subtitle">\${s.summary}</p><div class="quote-mark">“</div><h2 id="quoteToggle" class="today-quote \${s.original?'quote-toggle':''} \${orig?'showing':''}" style="font-size:48px">\${orig&&s.original?s.original:s.quote}</h2>\${orig&&s.original?'<span class="original-label">(original text)</span>':''}<div class="source mono">\${s.source}</div><div class="reader-actions"><button class="pill" id="copy">▣ Copy</button></div><section class="specimen-section"><div class="specimen-section-title"><div class="teaching-icon">⌁</div><div class="mono">Historical Context</div></div><p class="acc-body">\${s.context}</p></section><section class="specimen-section"><div class="specimen-section-title"><div class="teaching-icon">◐</div><div class="mono">What It Teaches</div></div><p class="acc-body">\${s.teaches}</p></section><section class="specimen-section" id="deploy"><div class="specimen-section-title"><div class="teaching-icon">✓</div><div class="mono">Deploy Today</div></div><div class="acc-body dosgrid"><div class="doscol"><b>Do</b><ul>\${s.dos.map(x=>\`<li>\${x}</li>\`).join('')}</ul></div><div class="doscol"><b>Do not</b><ul>\${s.donts.map(x=>\`<li>\${x}</li>\`).join('')}</ul></div></div></section>\`;$('#close').onclick=()=>{let back=st.returnTab||'gallery';st.detail='';st.returnTab='';save();if(back==='today'){st.tab='today';render()}else gallery()};$('#saveD').onclick=()=>toggleSave(s.id);let qt=$('#quoteToggle');if(qt&&s.original)qt.onclick=()=>{st.orig=orig?'':s.id;detail()};$('#copy').onclick=()=>{navigator.clipboard?.writeText(\`\${s.quote}\\n— \${s.source}\`);show('Copied')};bump('practiced',s.id)}
`;
if (!h.includes('function openSpecimenFromToday')) h = h.replace('runTests();render();', patch + '\nrunTests();render();');
fs.writeFileSync(p, h);
